apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  source:
    path: ./argocd/apps
    repoURL: https://github.com/slappyslap/gocrawl.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
