apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongodb-cluster
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: mongodb
    targetRevision: 16.2.1
    helm:
      values: |
        architecture: replicaset

        auth:
          enabled: false

        replicaCount: 3

        persistence:
          enabled: true
          storageClass: nfs-storage
          accessModes:
            - ReadWriteMany

        service:
          enabled: true
          type: ClusterIP

        resources:
          requests:
            cpu: 500m
            memory: 1Gi
          limits:
            cpu: 1
            memory: 2Gi

        startupProbe:
          enabled: true
          initialDelaySeconds: 30

        updateStrategy:
          type: RollingUpdate

        volumePermissions:
          enabled: true

  destination:
    server: https://kubernetes.default.svc
    namespace: gocrawl

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true