apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongodb-cluster
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: mongodb
    targetRevision: 16.2.1
    helm:
      values: |
        architecture: replicaset

        auth:
          enabled: false

        # Configuration du cluster
        replicaCount: 3

        # Persistent Storage
        persistence:
          enabled: true
          storageClass: local-path  # Adaptez à votre storage class
          size: 10Gi

        # Configuration réseau
        service:
          enabled: true
          type: ClusterIP

        # Configuration des ressources
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
          limits:
            cpu: 1
            memory: 2Gi

        # Probes de santé
        startupProbe:
          enabled: true
          initialDelaySeconds: 30

        # Configuration des volumes
        volumePermissions:
          enabled: true

        # Configuration avancée du replica set
        arbiter:
          enabled: true

        # Politique de mise à jour
        updateStrategy:
          type: RollingUpdate

  destination:
    server: https://kubernetes.default.svc
    namespace: gocrawl

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true